# Generated by Django 4.2.24 on 2025-09-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=255)),
                ('location_address', models.TextField()),
                ('location_timezone', models.CharField(max_length=100)),
                ('location_call_number', models.CharField(blank=True, max_length=20, null=True)),
                ('location_transfer_number', models.CharField(blank=True, max_length=20, null=True)),
                ('location_google_map_link', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
