# Generated by Django 4.2.24 on 2025-10-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_hoursofoperation_ending_day_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdaypartypackage',
            name='each_additional_jump_half_hour_after_room_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
