# Generated by Django 4.2.24 on 2025-10-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_birthdaypartypackage_each_additional_jump_half_hour_after_room_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoursofoperation',
            name='ages_allowed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hoursofoperation',
            name='schedule_with',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
