# Generated by Django 4.2.24 on 2025-10-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_hoursofoperation_ages_allowed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoursofoperation',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoursofoperation',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
