# Generated by Django 4.2.24 on 2025-10-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_hoursofoperation_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumppass',
            name='tax_included',
            field=models.BooleanField(default=False, help_text='Check if tax is included in the price (Yes/No or 1/0).'),
        ),
    ]
