# Generated by Django 4.2.24 on 2025-10-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_jumppass_tax_included'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumppass',
            name='tax_included',
            field=models.BooleanField(help_text='Check if tax is included in the price (Yes/No or 1/0).'),
        ),
    ]
