# Generated by Django 4.2.24 on 2025-10-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_jumppass_tax_included'),
    ]

    operations = [
        migrations.AddField(
            model_name='jumppass',
            name='tax_percentage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
