# Generated by Django 4.2.24 on 2025-10-23 06:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_jumppass_tax_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoursofoperation',
            name='same_entry_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
