# Generated by Django 4.2.24 on 2025-10-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_hoursofoperation_same_entry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoursofoperation',
            name='same_entry_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
