# Generated by Django 4.2.24 on 2025-10-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_hoursofoperation_same_entry_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jumppass',
            name='tax_percentage',
        ),
        migrations.AddField(
            model_name='jumppass',
            name='can_custom_take_part_in_multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jumppass',
            name='schedule_with',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
