# Generated by Django 4.2.24 on 2025-10-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_jumppass_tax_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jumppass',
            name='roller_booking_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
