# Generated by Django 4.2.24 on 2025-10-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_jumppass_roller_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumppass',
            name='roller_booking_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
