# Generated by Django 4.2.24 on 2025-10-31 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_jumppass_roller_booking_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('membership_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('schedule_with', models.JSONField(default=list)),
                ('pitch_priority', models.IntegerField()),
                ('pitch_introduction', models.TextField(blank=True, null=True)),
                ('activity_time', models.CharField(blank=True, max_length=255, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('party_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parent_addon_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subscription', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_included', models.BooleanField(help_text='Check if tax is included in the price (Yes/No or 1/0).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='myapp.location')),
            ],
            options={
                'db_table': 'memberships',
                'ordering': ['pitch_priority'],
            },
        ),
    ]
