# Generated by Django 4.2.24 on 2025-10-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='activity_time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
