# Generated by Django 4.2.24 on 2025-10-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_membership_activity_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
