# Generated by Django 4.2.24 on 2025-11-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_membership_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdaypartypackage',
            name='Is_additional_jumpers_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
