# Generated by Django 4.2.26 on 2025-11-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdaypartypackage',
            name='tax_included',
            field=models.BooleanField(default=True),
        ),
    ]
