# Generated by Django 4.2.26 on 2025-11-18 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('promotion_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_day', models.CharField(blank=True, help_text='e.g., Monday, Tuesday', max_length=20, null=True)),
                ('end_day', models.CharField(blank=True, help_text='e.g., Friday, Saturday', max_length=20, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('schedule_type', models.CharField(choices=[('one_time', 'One Time'), ('recurring_daily', 'Recurring Daily'), ('recurring_weekly', 'Recurring Weekly'), ('recurring_monthly', 'Recurring Monthly')], default='one_time', max_length=20)),
                ('promotion_code', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('eligibility_type', models.CharField(choices=[('all_customers', 'All Customers'), ('new_customers', 'New Customers Only'), ('existing_customers', 'Existing Customers Only'), ('members_only', 'Members Only'), ('first_time_visitors', 'First Time Visitors'), ('min_purchase', 'Minimum Purchase Amount'), ('min_visit', 'Minimum Visit Count')], default='all_customers', max_length=50)),
                ('constraint_value', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum amount or count required', max_digits=10, null=True)),
                ('instructions', models.TextField(blank=True, help_text='How to redeem or use this promotion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='myapp.location')),
            ],
            options={
                'db_table': 'promotions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['promotion_code'], name='promotions_promoti_8eef7e_idx'), models.Index(fields=['start_date', 'end_date'], name='promotions_start_d_e0aba6_idx'), models.Index(fields=['category'], name='promotions_categor_24b585_idx')],
            },
        ),
    ]
