# Generated by Django 4.2.26 on 2025-11-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='schedule_type',
            field=models.CharField(default='one_time', max_length=20),
        ),
    ]
