# Generated by Django 4.2.26 on 2025-11-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_promotion_schedule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='eligibility_type',
            field=models.CharField(default='all_customers', max_length=50),
        ),
    ]
