# Generated by Django 4.2.26 on 2025-11-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_promotion_eligibility_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the promotion is currently active'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='constraint_value',
            field=models.CharField(blank=True, help_text='Constraint value (can be text, number, or any format)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='eligibility_type',
            field=models.CharField(default='birthday_party_purchase', max_length=50),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='schedule_type',
            field=models.CharField(default='always_active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['is_active'], name='promotions_is_acti_5031c3_idx'),
        ),
    ]
