# Generated by Django 4.2.26 on 2025-11-24 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_birthdaypartypackage_is_any_balloon_package_is_free'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalFacility',
            fields=[
                ('rental_facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('rental_jumper_group', models.CharField(max_length=255)),
                ('call_flow_priority', models.IntegerField()),
                ('per_jumper_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_jumpers', models.IntegerField()),
                ('instruction', models.TextField(blank=True, null=True)),
                ('inclusions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_facilities', to='myapp.location')),
            ],
            options={
                'db_table': 'rental_facility',
                'ordering': ['call_flow_priority'],
                'unique_together': {('location', 'rental_jumper_group')},
            },
        ),
    ]
