# Generated by Django 4.2.26 on 2025-11-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_groupbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='add_additional_half_hour_of_jump_instruction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='add_additional_hour_of_jump_instruction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='add_party_space_sentence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='add_shirts_while_booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='additional_jumper_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='elite_member_party_discount_percentage',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='location',
            name='from_email_address',
            field=models.EmailField(default='shereen@purpledesk.ai', max_length=254),
        ),
        migrations.AddField(
            model_name='location',
            name='glow_age_bracket',
            field=models.CharField(default='Recommended for Kids of 3 years old and above', max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='guest_of_honor_included_in_minimum_jumpers_party',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='is_booking_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='is_edit_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='little_leaper_age_bracket',
            field=models.CharField(default='Recommended for Kids of age 6 years old and under', max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='membership_cancellation_days',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='location',
            name='minimum_deposit_required_for_booking',
            field=models.CharField(default='50 percent', max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='minimum_jumpers_party',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='location',
            name='party_booking_allowed_days_before_party_date',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='location',
            name='party_reschedule_allowed_before_party_date_days',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='location',
            name='pitch_ballons_while_booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='pitch_group_rates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='pitch_rental_facility',
            field=models.BooleanField(default=True),
        ),
    ]
