# Generated by Django 4.2.26 on 2025-11-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_jumppass_roller_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsfooddrinks',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
