# Generated by Django 4.2.26 on 2025-11-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_promotion_eligibility_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='promotion_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
