# Generated by Django 4.2.26 on 2025-11-12 10:34

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalloonPartyPackage',
            fields=[
                ('balloon_party_packages_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=255)),
                ('call_flow_priority', models.IntegerField()),
                ('promotional_pitch', models.TextField(blank=True, null=True)),
                ('package_inclusions', models.TextField(blank=True, null=True)),
                ('discount', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'balloon_party_packages',
                'ordering': ['call_flow_priority'],
            },
        ),
        migrations.CreateModel(
            name='BirthdayBalloonBridge',
            fields=[
                ('birthday_balloon_bridge_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balloon_party_package', models.ForeignKey(db_column='balloon_party_packages_id', on_delete=django.db.models.deletion.CASCADE, related_name='birthday_packages_bridge', to='myapp.balloonpartypackage')),
            ],
            options={
                'db_table': 'birthday_balloon_bridge',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=255, unique=True)),
                ('location_address', models.TextField()),
                ('location_timezone', models.CharField(max_length=100)),
                ('location_call_number', models.CharField(blank=True, max_length=20, null=True)),
                ('location_transfer_number', models.CharField(blank=True, max_length=20, null=True)),
                ('location_google_map_link', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('membership_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('schedule_with', models.JSONField(default=list)),
                ('pitch_priority', models.IntegerField()),
                ('pitch_introduction', models.TextField(blank=True, null=True)),
                ('activity_time', models.TextField(blank=True, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('party_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parent_addon_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('subscription', models.CharField(blank=True, max_length=255, null=True)),
                ('tax_included', models.BooleanField(help_text='Check if tax is included in the price (Yes/No or 1/0).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='myapp.location')),
            ],
            options={
                'db_table': 'memberships',
                'ordering': ['pitch_priority'],
            },
        ),
        migrations.CreateModel(
            name='JumpPass',
            fields=[
                ('jump_pass_id', models.AutoField(primary_key=True, serialize=False)),
                ('jump_pass_priority', models.IntegerField()),
                ('schedule_with', models.JSONField(blank=True, default=list, null=True)),
                ('pass_name', models.CharField(max_length=255)),
                ('age_allowed', models.CharField(max_length=255)),
                ('jump_time_allowed', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_included', models.BooleanField(help_text='Check if tax is included in the price (Yes/No or 1/0).')),
                ('can_custom_take_part_in_multiple', models.BooleanField(default=False)),
                ('recommendation', models.TextField()),
                ('jump_pass_pitch', models.TextField(blank=True, null=True)),
                ('starting_day_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ending_day_name', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('roller_booking_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jump_passes', to='myapp.location')),
            ],
            options={
                'db_table': 'jump_passes',
                'ordering': ['jump_pass_priority'],
            },
        ),
        migrations.CreateModel(
            name='HoursOfOperation',
            fields=[
                ('hours_of_operation_id', models.AutoField(primary_key=True, serialize=False)),
                ('hours_type', models.CharField(max_length=100)),
                ('schedule_with', models.CharField(blank=True, max_length=100, null=True)),
                ('ages_allowed', models.CharField(blank=True, max_length=50, null=True)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('starting_day_name', models.CharField(max_length=20)),
                ('ending_day_name', models.CharField(blank=True, max_length=20, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_modified', models.BooleanField(default=False)),
                ('same_entry_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.location')),
            ],
            options={
                'db_table': 'hours_of_operation',
            },
        ),
        migrations.CreateModel(
            name='BirthdayPartyPackage',
            fields=[
                ('birthday_party_packages_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=255)),
                ('birthday_party_priority', models.IntegerField()),
                ('availability_days', models.CharField(max_length=255)),
                ('schedule_with', models.CharField(max_length=255)),
                ('minimum_jumpers', models.IntegerField()),
                ('jump_time', models.CharField(max_length=255)),
                ('party_room_time', models.CharField(max_length=255)),
                ('food_and_drinks', models.CharField(max_length=500)),
                ('paper_goods', models.CharField(max_length=255)),
                ('skysocks', models.CharField(max_length=255)),
                ('dessert_policy', models.CharField(max_length=255)),
                ('other_perks', models.CharField(max_length=500)),
                ('outside_food_drinks_fee', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guest_of_honour_included_in_total_jumpers', models.BooleanField(default=False)),
                ('tax_included', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax percentage (e.g., 10.00 for 10%)', max_digits=5)),
                ('birthday_party_booking_lead_allowed_days', models.IntegerField()),
                ('birthday_party_reschedule_allowed_days', models.IntegerField()),
                ('each_additional_jumper_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('birthday_party_pitch', models.TextField(blank=True, null=True)),
                ('Is_additional_jumpers_allowed', models.BooleanField(default=True)),
                ('each_additional_jump_hour_after_room_time', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_instructions', models.TextField(blank=True, null=True)),
                ('birthday_party_discount_code', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday_party_discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('roller_birthday_party_search_id', models.CharField(blank=True, max_length=255, null=True)),
                ('roller_additional_jumper_price_search_id', models.CharField(blank=True, max_length=255, null=True)),
                ('roller_birthday_party_booking_id', models.CharField(blank=True, max_length=255, null=True)),
                ('each_additional_jump_half_hour_after_room_time', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balloon_packages', models.ManyToManyField(related_name='birthday_party_packages', through='myapp.BirthdayBalloonBridge', to='myapp.balloonpartypackage')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_party_packages', to='myapp.location')),
            ],
            options={
                'db_table': 'birthday_party_packages',
                'ordering': ['birthday_party_priority'],
            },
        ),
        migrations.AddField(
            model_name='birthdayballoonbridge',
            name='birthday_party_package',
            field=models.ForeignKey(db_column='birthday_party_packages_id', on_delete=django.db.models.deletion.CASCADE, related_name='balloon_packages_bridge', to='myapp.birthdaypartypackage'),
        ),
        migrations.AddField(
            model_name='balloonpartypackage',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balloon_party_packages', to='myapp.location'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('bot', 'Bot')], default='bot', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='birthdayballoonbridge',
            unique_together={('birthday_party_package', 'balloon_party_package')},
        ),
    ]
