# Generated by Django 4.2.26 on 2025-11-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='minimum_deposit_required_for_booking',
            field=models.CharField(default='50 percents', max_length=50),
        ),
    ]
