# Generated by Django 4.2.26 on 2025-11-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_location_minimum_deposit_required_for_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdaypartypackage',
            name='balloon_package_included',
            field=models.BooleanField(default=True),
        ),
    ]
