# Generated by Django 4.2.26 on 2025-11-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_birthdaypartypackage_balloon_package_included'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdaypartypackage',
            name='balloon_package_included',
            field=models.BooleanField(default=False),
        ),
    ]
