# Generated by Django 5.2.6 on 2025-09-16 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_location_location_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoursOfOperation',
            fields=[
                ('hours_of_operation_id', models.AutoField(primary_key=True, serialize=False)),
                ('hours_type', models.CharField(max_length=100)),
                ('schedule_with', models.CharField(max_length=100)),
                ('ages_allowed', models.CharField(max_length=50)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('starting_day_name', models.CharField(max_length=20)),
                ('ending_day_name', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_modified', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.location')),
            ],
            options={
                'db_table': 'hours_of_operation',
            },
        ),
    ]
