# Generated by Django 4.2.26 on 2025-11-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_birthdaypartypackage_balloon_package_included'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsfooddrinks',
            name='category_type',
            field=models.CharField(blank=True, max_length=101, null=True),
        ),
    ]
