# Generated by Django 5.2.6 on 2025-09-17 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_hoursofoperation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayPartyPackage',
            fields=[
                ('birthday_party_packages_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=255)),
                ('birthday_party_priority', models.IntegerField()),
                ('availability_days', models.CharField(max_length=255)),
                ('schedule_with', models.CharField(max_length=255)),
                ('minimum_jumpers', models.IntegerField()),
                ('jump_time', models.CharField(max_length=255)),
                ('party_room_time', models.CharField(max_length=255)),
                ('food_and_drinks', models.CharField(max_length=500)),
                ('paper_goods', models.CharField(max_length=255)),
                ('skysocks', models.CharField(max_length=255)),
                ('dessert_policy', models.CharField(max_length=255)),
                ('other_perks', models.CharField(max_length=500)),
                ('outside_food_drinks_fee', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guest_of_honour_included_in_total_jumpers', models.BooleanField(default=False)),
                ('tax_included', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax percentage (e.g., 10.00 for 10%)', max_digits=5)),
                ('birthday_party_booking_lead_allowed_days', models.IntegerField()),
                ('birthday_party_reschedule_allowed_days', models.IntegerField()),
                ('each_additional_jumper_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('birthday_party_pitch', models.TextField(blank=True, null=True)),
                ('each_additional_jump_hour_after_room_time', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_instructions', models.TextField(blank=True, null=True)),
                ('birthday_party_discount_code', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday_party_discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('roller_birthday_party_search_id', models.CharField(blank=True, max_length=255, null=True)),
                ('roller_additional_jumper_price_search_id', models.CharField(blank=True, max_length=255, null=True)),
                ('roller_birthday_party_booking_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_party_packages', to='myapp.location')),
            ],
            options={
                'db_table': 'birthday_party_packages',
                'ordering': ['birthday_party_priority'],
            },
        ),
    ]
