# Generated by Django 4.2.26 on 2025-12-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_itemsfooddrinks_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdaypartypackage',
            name='dessert_policy',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='birthdaypartypackage',
            name='food_and_drinks',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='birthdaypartypackage',
            name='outside_food_drinks_fee',
            field=models.CharField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='birthdaypartypackage',
            name='paper_goods',
            field=models.CharField(max_length=2550),
        ),
    ]
