# Generated by Django 5.2.6 on 2025-09-18 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_birthdaypartypackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='JumpPass',
            fields=[
                ('jump_pass_id', models.AutoField(primary_key=True, serialize=False)),
                ('jump_pass_priority', models.IntegerField()),
                ('schedule_with', models.CharField(max_length=255)),
                ('pass_name', models.CharField(max_length=255)),
                ('age_allowed', models.CharField(max_length=255)),
                ('jump_time_allowed', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_included', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax percentage (e.g., 10.00 for 10%)', max_digits=5)),
                ('recommendation', models.TextField()),
                ('jump_pass_pitch', models.TextField(blank=True, null=True)),
                ('starting_day_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ending_day_name', models.CharField(blank=True, max_length=50, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jump_passes', to='myapp.location')),
            ],
            options={
                'db_table': 'jump_passes',
                'ordering': ['jump_pass_priority'],
            },
        ),
    ]
