# Generated by Django 4.2.26 on 2025-12-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_birthdaypartypackage_dessert_policy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdaypartypackage',
            name='outside_food_drinks_fee',
            field=models.TextField(),
        ),
    ]
