# Generated by Django 5.2.6 on 2025-09-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_jumppass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoursofoperation',
            name='ending_day_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
