# Generated by Django 4.2.26 on 2025-12-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_birthdaypartypackage_outside_food_drinks_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumppass',
            name='roller_booking_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
