# Generated by Django 4.2.26 on 2025-11-19 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_promotion_is_active_alter_promotion_constraint_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsFoodDrinks',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('category_priority', models.IntegerField(default=0, help_text='Priority for category ordering')),
                ('category_type', models.CharField(blank=True, max_length=100, null=True)),
                ('options_type_per_category', models.CharField(blank=True, max_length=100, null=True)),
                ('item', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_instructions', models.TextField(blank=True, null=True)),
                ('t_shirt_sizes', models.CharField(blank=True, help_text='Comma-separated sizes if applicable', max_length=255, null=True)),
                ('t_shirt_type', models.CharField(blank=True, max_length=100, null=True)),
                ('pitch_in_party_package', models.BooleanField(default=False, help_text='Whether this item is included in party packages')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_drink_items', to='myapp.location')),
            ],
            options={
                'verbose_name': 'Food Drink Item',
                'verbose_name_plural': 'Food Drink Items',
                'db_table': 'items_food_drinks',
                'ordering': ['category_priority', 'category', 'item'],
                'indexes': [models.Index(fields=['location', 'category'], name='items_food__locatio_c5347c_idx'), models.Index(fields=['category'], name='items_food__categor_9350b8_idx'), models.Index(fields=['pitch_in_party_package'], name='items_food__pitch_i_177a30_idx'), models.Index(fields=['category_priority'], name='items_food__categor_5a529c_idx')],
            },
        ),
    ]
