# Generated by Django 4.2.26 on 2025-12-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_jumppass_roller_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumppass',
            name='roller_booking_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
