# Generated by Django 4.2.26 on 2025-12-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_jumppass_roller_booking_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentalfacility',
            options={},
        ),
        migrations.RenameField(
            model_name='rentalfacility',
            old_name='call_flow_priority',
            new_name='maximum_jumpers',
        ),
        migrations.RemoveField(
            model_name='rentalfacility',
            name='instruction',
        ),
        migrations.AddField(
            model_name='rentalfacility',
            name='rental_group_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
