# Generated by Django 4.2.26 on 2025-11-24 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_itemsfooddrinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthdaypartypackage',
            name='balloon_packages',
        ),
        migrations.AddField(
            model_name='birthdaypartypackage',
            name='balloon_package_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='birthdaypartypackage',
            name='balloon_party_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birthday_party_packages', to='myapp.balloonpartypackage'),
        ),
        migrations.AddField(
            model_name='birthdaypartypackage',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='birthdaypartypackage',
            name='promotion_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='BirthdayBalloonBridge',
        ),
    ]
