# Generated by Django 4.2.26 on 2025-11-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_birthdaypartypackage_balloon_packages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdaypartypackage',
            name='is_any_balloon_package_is_free',
            field=models.BooleanField(default=False),
        ),
    ]
