# Generated by Django 4.2.26 on 2025-12-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_rentalfacility_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='policy',
            unique_together=set(),
        ),
    ]
