# Generated by Django 4.2.26 on 2025-12-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_policy_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
