# Generated by Django 4.2.26 on 2025-11-25 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rentalfacility'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBooking',
            fields=[
                ('group_booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_packages', models.CharField(max_length=255)),
                ('call_flow_priority', models.IntegerField()),
                ('flat_fee_jumper_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_jumpers', models.IntegerField()),
                ('instruction', models.TextField(blank=True, null=True)),
                ('package_inclusions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_bookings', to='myapp.location')),
            ],
            options={
                'db_table': 'group_booking',
                'ordering': ['call_flow_priority'],
                'unique_together': {('location', 'group_packages')},
            },
        ),
    ]
