# Generated by Django 4.2.26 on 2025-12-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rollerapicredentials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AddField(
            model_name='location',
            name='roller_access_token',
            field=models.TextField(blank=True, null=True, verbose_name='Roller Access Token'),
        ),
        migrations.AddField(
            model_name='location',
            name='roller_category_name',
            field=models.CharField(blank=True, default='TESTB', max_length=100, null=True, verbose_name='Roller Category'),
        ),
        migrations.AddField(
            model_name='location',
            name='roller_client_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Roller Client ID'),
        ),
        migrations.AddField(
            model_name='location',
            name='roller_client_secret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Roller Client Secret'),
        ),
        migrations.AddField(
            model_name='location',
            name='roller_deposit_percentage',
            field=models.IntegerField(default=50, verbose_name='Deposit Percentage'),
        ),
        migrations.AddField(
            model_name='location',
            name='roller_max_capacity',
            field=models.IntegerField(default=30, verbose_name='Max Capacity'),
        ),
        migrations.AddField(
            model_name='location',
            name='roller_product_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Default Roller Product ID'),
        ),
        migrations.AddField(
            model_name='location',
            name='roller_token_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Token Created At'),
        ),
        migrations.DeleteModel(
            name='RollerAPICredentials',
        ),
    ]
