# Generated by Django 4.2.26 on 2025-11-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_location_add_additional_half_hour_of_jump_instruction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('bot', 'Bot')], default='admin', max_length=10),
        ),
    ]
