# Generated by Django 4.2.26 on 2025-12-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_location_options_location_roller_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='roller_category_name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='roller_deposit_percentage',
        ),
        migrations.RemoveField(
            model_name='location',
            name='roller_max_capacity',
        ),
        migrations.RemoveField(
            model_name='location',
            name='roller_product_id',
        ),
    ]
