# Generated by Django 4.2.26 on 2025-11-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthdaypartypackage',
            name='birthday_party_booking_lead_allowed_days',
        ),
        migrations.RemoveField(
            model_name='birthdaypartypackage',
            name='birthday_party_reschedule_allowed_days',
        ),
        migrations.AddField(
            model_name='birthdaypartypackage',
            name='drinks_included_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='birthdaypartypackage',
            name='food_included_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='birthdaypartypackage',
            name='party_environment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='birthdaypartypackage',
            name='perks_for_guest_of_honor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
