# Generated by Django 4.2.26 on 2025-12-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_location_roller_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('roller_customer_id', models.CharField(max_length=255)),
            ],
        ),
    ]
