# Generated by Django 4.2.26 on 2025-12-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_customerdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='roller_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
