# Generated by Django 4.2.26 on 2025-11-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_birthdaypartypackage_birthday_party_booking_lead_allowed_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumppass',
            name='roller_booking_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
