# Generated by Django 4.2.26 on 2025-12-30 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_customerdetails_roller_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='RollerBookingDetails',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('roller_id', models.CharField(max_length=50)),
                ('booking_unique_id', models.CharField(blank=True, max_length=255, null=True)),
                ('booking_date', models.CharField(blank=True, max_length=255, null=True)),
                ('booking_time', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity_reservation_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_made', models.BooleanField(default=False)),
                ('payload', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Foreign key to CustomerDetails table', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='myapp.customerdetails')),
            ],
        ),
    ]
