# Generated by Django 4.2.26 on 2025-11-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_itemsfooddrinks_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='promotion_code',
            field=models.CharField(max_length=100),
        ),
    ]
