# Generated by Django 4.2.26 on 2025-12-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_customerdetails_last_name_rollerbookingdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollerbookingdetails',
            name='payload',
            field=models.TextField(blank=True, null=True),
        ),
    ]
