# Generated by Django 4.2.26 on 2025-11-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_promotion_promotion_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='eligibility_type',
            field=models.CharField(max_length=50),
        ),
    ]
