# Generated by Django 4.2.26 on 2025-12-30 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_rollerbookingdetails_payload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rollerbookingdetails',
            old_name='customer',
            new_name='customer_id',
        ),
    ]
