# Generated by Django 4.2.26 on 2025-12-30 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_rename_customer_rollerbookingdetails_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rollerbookingdetails',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
