# Generated by Django 4.2.26 on 2025-11-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_promotion_promotion_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='eligibility_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
