# Generated by Django 4.2.26 on 2026-01-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_rename_customer_id_rollerbookingdetails_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rollerbookingdetails',
            name='capacity_reservation_id',
        ),
        migrations.AddField(
            model_name='rollerbookingdetails',
            name='deposite_made',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
