# Generated by Django 4.2.26 on 2025-11-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_promotion_eligibility_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='parent_addon_price',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
