# Generated by Django 4.2.26 on 2026-01-03 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_rollerbookingdetails_capacity_reservation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rollerbookingdetails',
            name='deposite_made',
        ),
        migrations.AddField(
            model_name='rollerbookingdetails',
            name='booking_status',
            field=models.CharField(default='live', max_length=50),
        ),
        migrations.AddField(
            model_name='rollerbookingdetails',
            name='deposit_made_in_doller',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rollerbookingdetails',
            name='is_booking_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rollerbookingdetails',
            name='location_id',
            field=models.ForeignKey(help_text='Foreign key to Location table', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_location', to='myapp.location'),
        ),
    ]
