# Generated by Django 4.2.26 on 2026-01-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_rollerbookingdetails_deposite_made_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollerbookingdetails',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
