# Generated by Django 4.2.26 on 2026-01-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_rollerbookingdetails_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollerbookingdetails',
            name='roller_booking_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='rollerbookingdetails',
            index=models.Index(fields=['external_id'], name='myapp_rolle_externa_40305e_idx'),
        ),
        migrations.AddIndex(
            model_name='rollerbookingdetails',
            index=models.Index(fields=['booking_status'], name='myapp_rolle_booking_1c96a7_idx'),
        ),
        migrations.AddIndex(
            model_name='rollerbookingdetails',
            index=models.Index(fields=['is_booking_paid'], name='myapp_rolle_is_book_89fe61_idx'),
        ),
    ]
